# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 46c17e563450af35c16945bc32d4db3d079cf444c026a579628c820161025f2b51a2ce6d94122c92350d363284dd0051b8efc30e7f6822e741641f69d05035bf

test:
  secret_key_base: 64539224e4cbc58f66b5118bdf2db63b1730769edd5e526cd6eb600d0506c8563649b5ffd0c9f4ef5812638cc08ebd53eb626141394d3faacc022c820f63d4ab

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
